### ISSUE TITLE
Continuous integration testing for all supported python versions

### ISSUE THREAD

**Issue by alejandrogallo** [mishioo/tesliper#2]
In the readme you mention support for python3.6+ as well as in the pypi
package https://pypi.org/project/tesliper/ and `setup.py` file,
however the testing is done only for `python3.6`, could
you update the testing in order to comply with the targeted versions?

Using gihtub actions this can be done by adapting
a yaml file like this one

```yaml
name: CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install -U pip
        python -m pip install -r requirements.txt
        python -m pip install pytest
        python -m pip install pytest-cov
        python -m pip install hypothesis
        python -m pip install coveralls
        ./tools/ci-install.sh
      shell: bash
    - name: Run tests
      run: |
        python -m pytest --cov=tesliper --cov-config=.coveragerc test
      shell: bash
```
